### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by EmilyMansfield** [Piepenguin1995/rfwindmill#15]
The rotor textures are pretty bad, they could definitely do with an update.

**Comment by rdelro** [comment]
Leaving this here just in case you didn't get it: http://imgur.com/R88i7Wx,uqjf4nN,n9ST5LK,Qjk2AAu#0 Textures we hope you like them! We can edit them however you like.

**Comment by EmilyMansfield** [comment]
They look great! Maybe make the rotor icons a little thinner so they fit better with the model?

**Comment by rdelro** [comment]
there slimmed out versions: http://imgur.com/bnH5JAL is this better?

**Comment by EmilyMansfield** [comment]
Yes that's better, thanks! Could you fork this project and then submit a pull request to the dev branch with the new textures added so I can merge them in?

**Comment by rdelro** [comment]
Yes! However I won't be able to do that until later. I gotta go to the doctor all day today..

**Comment by EmilyMansfield** [comment]
That's alright, there's no rush! Health comes first :)

**Comment by rdelro** [comment]
Thanks! I just got home not long ago. Anyways I'm quite new to github and highly unfamiliar with it's layout..ahem but here http://derpy.me/Gh1My that contains the textures.

**Comment by EmilyMansfield** [comment]
No worries, I'll merge them in myself. If you've used git before then there's a [nice tutorial on it](https://help.github.com/articles/using-pull-requests/) for future reference since they're nicer to use than submitting files but it doesn't matter. Thanks for the help!

**Comment by rdelro** [comment]
Apologies! Thank you for the info, I'll be sure to try this out next time if you need us to do textures for you in the future.

**Comment by EmilyMansfield** [comment]
Thanks, I've just merged the textures into the dev branch so they'll be in the next release.
