### ISSUE TITLE
Thermal Expansion upgrades

### ISSUE THREAD

**Issue by EmilyMansfield** [Piepenguin1995/rfwindmill#16]
Dyanmos in Thermal Expansion support several upgrades used to boost their efficiency. The same feature could be implemented here, but that would also mean creating a GUI system for the turbines, which could be a little bit of overkill.

**Comment by rdelro** [comment]
Would it be easier to add recipes for 'upgraded' machines? ie: basic block (4rf/t) + upgrades/parts/whatever = (upgraded/powered/enhanced) basic windmill, which pushes x2 what a non-upgraded one would do. Granted you might not be able to downgrade it, but you can upgrade it to the 'final' tier (assuming resonant.) Just a thought.

**Comment by EmilyMansfield** [comment]
That's certainly a possibility since with the new update the metadata of the windmill block has been freed to be used for other purposes (it used to be use for direction), however I'd like to retain the ability to directly craft high-tier windmills using the existing recipes so the upgrade recipes would have to be carefully made so as to be equivalent. 

Having said that this would certainly be simpler and easier to implement and wouldn't force a Thermal Expansion dependency, so I'll think about it, thanks for the suggestion.

**Comment by EmilyMansfield** [comment]
Quick update, I don't think upgrades are entirely a crucial feature so I'll be making them conditional based on the presence of Thermal Expansion, but I've also added upgrade recipes to turn each windmill into its next tier which will be available in both vanilla and Thermal Expansion/Foundation versions (although the recipes will obviously differ).
This is all set for the v0.6 release.

**Comment by EmilyMansfield** [comment]
I can't justify the power increase given by the upgrades since there's no equivalent of 'fuel consumption', so this won't be done until then. Closing for now, issue could be reopened at a later date, thanks for the suggestions.
