### ISSUE TITLE
0.6, All windmills drop basic windmills when broken

### ISSUE THREAD

**Issue by Rodg88** [Piepenguin1995/rfwindmill#18]
Placing a reinforced/hardened/resonant windmill, and breaking it with a pick or wrench will just drop a basic windmill. Tested in AgSkies 1.1.4

**Comment by EmilyMansfield** [comment]
Fixed as of commit 906856576d552a41cf2fa5c05ee1a981a3ea1414, can't believe I didn't notice that! My testing skills are abysmal, thanks for finding it! It'll be patched in the new version within a few minutes.
