### ISSUE TITLE
0.6 Reinforced and hardened windmills have wrong names

### ISSUE THREAD

**Issue by Rodg88** [Piepenguin1995/rfwindmill#19]
The reinforced windmill uses a hardened machine frame, while the hardened windmill uses a reinforced machine frame. Just need their names swapped.

**Comment by EmilyMansfield** [comment]
Thanks for spotting that, fixed as of commit ba8781a891d1adcb0b3aab25c15ff5368ada180d and will be patched into the main release shortly.
