### ISSUE TITLE
Manual turbines

### ISSUE THREAD

**Issue by EmilyMansfield** [Piepenguin1995/rfwindmill#23]
Could be a fun little feature to allow for manual operation of the windmills to generation electricity like AE2's hand-cranked macerator. Hold right click gives a certain (small) rotation speed regardless of altitude or tunnel space.

**Comment by rdelro** [comment]
I like this idea!

**Comment by EmilyMansfield** [comment]
That's good to hear! I've just integrated it into dev (commit d34ea64c35cb766dc7e828f9618d25b7476ff541) so it'll be in the next version.
