### ISSUE TITLE
Windmills stop when a block is placed behind them

### ISSUE THREAD

**Issue by MineCakeChase** [Piepenguin1995/rfwindmill#28]
Hello! I have been playing Agrarian Skies 2 lately and have been trying to get some power from your windmills. After a lot of testing I relised my problem was that I had a fluxduct plugged into the back of my windmill if the rotor's side is the front. When I removed it, the rotor spun fine and produced power. When I placed anything behind the windmill, the rotor stopped spinning but when i removed the offending block it worked.  I am not sure if this is a bug or if it is intended but I hope this helps.

**Comment by EmilyMansfield** [comment]
It's kind of intended, placing any block within a 3x3x20 tunnel centred on the windmill will reduce the power generated by a factor proportional to the distance from the windmill, so a block directly adjacent will stop the turbine. I wasn't sure whether to allow for a single block behind the rotor or not, and it was easier not to at the time. The wind wouldn't be able to flow there realistically though so I'll work on a patch to allow it.

**Comment by EmilyMansfield** [comment]
For some reason I fixed this then forgot to apply the patch for months, its applied in the most recent bugfix release v0.7b.
