### ISSUE TITLE
Crash on breaking rotor

### ISSUE THREAD

**Issue by xeronut** [Piepenguin1995/rfwindmill#29]
Hello!  I have a crash report for you:
http://pastebin.com/9FUtUAZQ
I get this when a rotor is placed in the correct blockspace adjacent to a windmill, but incorrect orientation.  Here is a pic describing the scenario:
http://i.imgur.com/y1KJnuN.png
Setup info should be detailed in screenshot.  Hope this helps!

**Comment by EmilyMansfield** [comment]
Sorry for the very late reply, that crash is a know issue but I wasn't aware that placing the rotors in an incorrect orientation was possible; it should have been patched several version ago. I guess its not too relevant now, so I'll close the issue unless you have it happen again.
