### ISSUE TITLE
3d Models

### ISSUE THREAD

**Issue by Empty2k12** [Piepenguin1995/rfwindmill#3]
^

**Comment by EmilyMansfield** [comment]
I thought about this, finding a shape that works is quite awkward though since a cuboid with a rotor inside as per the texture looks worse than the current textures. Any suggestions?

**Comment by Empty2k12** [comment]
Mekanism wind mills ;)

**Comment by K4N0** [comment]
Yes!!!

**Comment by EmilyMansfield** [comment]
Ok, I'm working on something similar now. I'm not a fan of how Mekanism forces the turbine to be a certain height so I'm sticking with the current single block structure but adding a new rotor block (rotors will be removed from recipes accordingly) which should be added to the front of the turbine in order for it to work. Should look sufficiently impressive but also adds flexibility to the height of the turbine towers.

**Comment by EmilyMansfield** [comment]
![2015-05-01_23 56 23](https://cloud.githubusercontent.com/assets/2227078/7440737/8266a10e-f0bd-11e4-8a18-5d6fa78b533c.png)
Preview for 0.5 windmills

**Comment by K4N0** [comment]
Yes!!, Very Nice!

**Comment by EmilyMansfield** [comment]
Completed as of commit 9931c460e01d6. Merged into dev branch and will be included in the next release, probably tomorrow.
