### ISSUE TITLE
Crash when breaking rotor above windmill block

### ISSUE THREAD

**Issue by ajthemacboy** [Piepenguin1995/rfwindmill#32]
https://gist.github.com/ajthemacboy/d42c5815b23e188737fd

**Comment by EmilyMansfield** [comment]
I think I've fixed the crash (for some bizarre reason I forgot to check for null in one place in the code), if you've still got the situation where you can replicate the crash, could you try with the [new binary](https://www.dropbox.com/s/g9khhu47fh1urv0/rfwindmill-1.7.10-0.7b.jar?dl=1) and see if it fixes the issue? I can't reproduce it myself.

**Comment by ajthemacboy** [comment]
Fixed! :)
