### ISSUE TITLE
Rotor Crash (wrong file on curseforge?)

### ISSUE THREAD

**Issue by ReTeYeZ** [Piepenguin1995/rfwindmill#33]
So I had this bug where destroying a rotor crashes the game even though
I downloaded the newest version on curseforge(0.7b). Since you couldn't reproduce
that bug and stated that it should be fixed a while ago I was searching a bit through the
comments/bug reports and found this:
https://github.com/Piepenguin1995/rfwindmill/issues/32

I tried the file you posted there and it worked immediatly, even though it has the same
name and size as the file from curseforge. Maybe you should take at look at that.

**Comment by EmilyMansfield** [comment]
That's because the version on CurseForge is not the newest version, I haven't uploaded it yet. I'll do it now.
