### ISSUE TITLE
Config file.

### ISSUE THREAD

**Issue by Pilad** [Piepenguin1995/rfwindmill#5]
Add the configuration file number of generated energy. Can add other generators? Eg water turbines, solar panels. Or steam, fuel generators.

**Comment by EmilyMansfield** [comment]
The excellent [solar flux](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2187592-solar-flux-a-k-a-compactsolars-for-redstone-flux) mod already creates solar panels, but a config file is a good idea and so are water turbines, which fit more with the theme of the mod.

**Comment by Pilad** [comment]
I would like to have one mod adds all types of generators. So as not to put a few mods.

**Comment by EmilyMansfield** [comment]
I understand, but I'm afraid complete energy generation is not currently in the scope of this mod. There does seem to be demand for more generators though (see issues #6, #7, #8, #9) so I'll consider it, thanks for your suggestions.

As for the config file, they've been incorporated into the development branch as of commit 14fe97b1 and will be included in the next release.
