### ISSUE TITLE
Thermal Generators

### ISSUE THREAD

**Issue by K4N0** [Piepenguin1995/rfwindmill#7]
Thermal generators, create power from lava being pumped in and source blocks around it.

**Comment by K4N0** [comment]
Or Fire

**Comment by EmilyMansfield** [comment]
I like the *nix philosophy of 'do one thing and do it well' so I don't think I'll be implementing this in this mod (Thermal Expansion already adds a lava powered dynamo). Surrounding lava and fire is an interesting idea though so I won't close this yet.

**Comment by K4N0** [comment]
ahh, yeah that's right, i was thinking mekanism heat gens.
I like the way you think.
